apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pagerduty-to-prometheus.fullname" . }}
  labels:
    {{- include "pagerduty-to-prometheus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pagerduty-to-prometheus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pagerduty-to-prometheus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pagerduty-to-prometheus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.pd.envSecrets }}
          envFrom:
            - secretRef:
                name: {{ .Values.pd.envSecrets }}
          {{- end }}
          env:
            {{- if .Values.pd.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.pd.logLevel | quote }}
            {{- end }}
            {{- if .Values.pd.lookbackDuration }}
            - name: LOOKBACK_DURATION
              value: {{ .Values.pd.lookbackDuration | quote }}
            {{- end }}
            {{- if .Values.pd.availabilityWindow }}
            - name: AVAILABILITY_WINDOW
              value: {{ .Values.pd.availabilityWindow | quote }}
            {{- end }}
            {{- if .Values.pd.refreshInterval }}
            - name: REFRESH_INTERVAL
              value: {{ .Values.pd.refreshInterval | quote }}
            {{- end }}
            {{- if .Values.pd.token }}
            - name: PAGERDUTY_TOKEN
              value: {{ .Values.pd.token | quote }}
            {{- end }}
            {{- if .Values.pd.tracer }}
            - name: TRACER
              value: {{ .Values.pd.tracer | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
